set(ASAN OFF)
set(UBSAN OFF)
set(NONET ON)
set(USE_SDL1 ON)
set(SDL1_VIDEO_MODE_BPP 8)
set(TTF_FONT_PATH \"LiberationSerif-Bold.ttf\")
# Enable exception suport as they are used in dvlnet code
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions")
find_package(Freetype REQUIRED)
find_package(ZLIB REQUIRED)
if(WARPOS)
  set(FASTER OFF)
  set(DEBUG OFF)
  set(DIST ON)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mcpu=603e -O3 -ffast-math -noixemul -D_POSIX_THREADS -DNDEBUG")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mcpu=603e -O3 -ffast-math -noixemul -fpermissive -D_POSIX_THREADS -DNDEBUG")
endif()